<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <center><?php echo $this->headTitle($this->translate('SensorCloud'))->setSeparator(' - ')->setAutoEscape(false) ?></center>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath()  ))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->prependFile($this->basepath() . '/js/jquery-1.7.2.min.js') ?>
                                      
        <?php $session = new \Zend\Session\Container('user');?>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('SensorCloud传感云平台') ?></a>
                    
                    <?php   if(!isset($_SESSION["username"])){ ?>
                       <div class="nav-collapse collapse">
                          <ul class="nav">
                              <li class="active"><a href="<?php echo $this->url('application',  array('action'=>'register'));?>"><?php echo $this->translate('注册') ?></a></li>
                          </ul>
                       </div><!--/.nav-collapse -->
                       <div class="nav-collapse collapse">
                          <ul class="nav">
                              <li class="active"><a href="<?php echo $this->url('application',array('action'=>'login')); ?>"><?php echo $this->translate('登录') ?></a></li>
                          </ul>
                       </div><!--/.nav-collapse -->
                     <?php }else{ ?>
                       <div class="nav-collapse collapse">
                          <ul class="nav">
                              <li class="active"><a><?php echo $this->translate('欢迎您：')?></a></li>
                              <li class="active"><a href="<?php echo $this->url('poster',array('action'=>'usercenter')); ?>"><?php echo $_SESSION["username"] ?></a></li>
                              <li class="active"><a href="<?php echo $this->url('application',array('action'=>'logout')); ?>"><?php echo $this->translate('退出登录')?></a></li>     
                          </ul>
                       </div><!--/.nav-collapse -->
                     <?php }?>
                    
                </div>
            </div>
        </div>
        </head>
        <?php echo $this->content; ?>
        <div class="container" align="right">
            <hr>
            <footer>
                <p>&copy; 2014 East China Normal University <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    
</html>
