<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
    <title>SensorCloud</title>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath()  ))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                         ->prependStylesheet($this->basePath() . '/css/style2.css')
//                         ->prependStylesheet($this->basePath() . '/css/style3.css')
                        
        ?>    
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
       
      <?php $session = new \Zend\Session\Container('user');?>  
     </head>
     <body class="home-theme bg">  
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                  
                    
                    <a class="navbar-brand hidden-sm" href="<?php echo $this->url('home') ?>" ><?php echo $this->translate('SensorCloud') ?> <font color='#13beec'><?php echo $this->translate('传感云平台') ?></font></a>
                     
                    <?php   if(!isset($_SESSION["username"])){ ?>
                       <div class="navbar-collapse collapse navbar-right" >
                          <ul class="nav navbar-nav">
                              <li class="active"><a href="<?php echo $this->url('application',  array('action'=>'register'));?>"><?php echo $this->translate('注册') ?></a></li>
                        
                              <li><a href="<?php echo $this->url('application',array('action'=>'login')); ?>"><?php echo $this->translate('登录') ?></a></li>
                          </ul>
                       </div><!--/.nav-collapse -->
                     <?php }else{ ?>
                       <div class="navbar-collapse collapse navbar-right">
                          <ul class="nav navbar-nav">
                              <li class="active" ><a><?php echo $_SESSION["username"];echo $this->translate(', 欢迎您!');?></a></li>
                              <li><a href="<?php echo $this->url('application',array('action'=>'usercenter')); ?>"><?php echo $this->translate('用户中心') ?></a></li>
                              <li ><a href="<?php echo $this->url('application',array('action'=>'logout')); ?>"><?php echo $this->translate('退出登录')?></a></li>     
                          </ul>
                       </div><!--/.nav-collapse -->
                     <?php }?>
                    
                </div>
            </div>
        </div>
        
        
        <?php echo $this->content; ?>
        <div class="container" align="right">
            <hr>
            <footer>
                <font color="white"><p>&copy; 2015 East China Normal University <?php echo $this->translate('All rights reserved.') ?></p></font>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        
         <!-- Scripts -->
         <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
         <!--  <script src="http://code.jquery.com/jquery-1.11.2.min.map"> </script> //开发者工具 -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ?>
                                      
    </body>
</html>
