<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<link href="/SensorCloud/public/css/bootstrap.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<link href="/SensorCloud/public/css/style.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- webfonts -->
<link href='http://fonts.googleapis.com/css?family=Arimo:400,700'
	rel='stylesheet' type='text/css'>
<!-- webfonts -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<?php
$title = '我订阅的服务';
$this->headTitle($title);
?>

<div class="page-header">
  <h2>我订阅的服务 </h2>
</div>

<?php   $subscriptions = $this->subscriptions;
        if(count($subscriptions)==0){?>
<p align="center">当前没有订阅服务</p>
<?php }else{ ?>
<table class="table table-bordered table-hover" align="center" bgcolor = "#99CCFF" >
<tr>
    <th  >服务名称</th>
    <th >服务类型</th>
    <th >服务位置</th>
    <th >过滤条件</th>
    <th >推送频率</th>
    <th>发布方</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($subscriptions as $subscription) : ?>
<tr>
    <td><?php echo $subscription->sensor_name;?></td>
    <td><?php echo $subscription->type;?></td>
    <td>(<?php echo $subscription->lat;?>,<?php echo $subscription->lon;?>)</td>
    <td><?php switch($subscription->filter){
    	           case 0: echo "无";break;
    	           case 1: echo "大于";break;
    	           case 2: echo "小于";break;
    	           case 3: echo "大于等于";break;
    	           case 4: echo "小于等于";break;
    	           case 5: echo "等于";break;
    	           case 6: echo "不等于";break;}?><?php echo $subscription->threshold_value;?></td>
    <td><?php switch($subscription->send_frequency){
                     case 1: echo "一分钟一次";break;
                     case 2: echo "一小时一次";break;
                     case 3: echo "六小时一次";break;
                     case 4: echo "一天一次";break;
    }?></td>
    <td><?php echo $subscription->puser_id;?></td>
    <td>
        <script language="javascript">
         function delcfm() {
            if (!confirm("确认退订该服务？")) {
                 window.event.returnValue = false;
             }
         }
        </script>
        <a href="<?php echo $this->url('subscriber',
            array('action'=>'deletesubscription','id' => $subscription->id));?>" onClick="delcfm()">删除</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php }?>

<div align="center" style="margin-top:15px; ">
     <button type="button" onclick="parent.parent.location.href = '<?php echo $this->url('subscriber',
                array('action'=>'subscriberindex'));?>'"><?php echo $this->translate('添加一个服务') ?></button>
</div>

<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
<script src="/SensorCloud/public/js/bootstrap.min.js"></script>