<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<body >


<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home', array(
            'action' => 'index'));?>">首页</a></li>
    <li><a href="<?php echo $this->url('subscriber',array('action' => 'subscriberindex'));?>">服务订阅</a></li>
    <li class="active">节点信息</li>
</ol>
<div class="col-md-offset-3 col-md-6 " >
    <p>&nbsp;</p>



    <div class="center-block" >
        <div class="panel panel-primary ">
            <div class="panel-heading">发布节点的信息</div>

            <table class="table table-bordered table-hover">
                <tr><th>名字</th><td><?php echo $this->sink->name ?></td></tr>
                <tr><th>位置</th><td>(<?php echo $this->sink->latitude ?>,<?php echo $this->sink->longitude ?>)</td></tr>
                <tr><th>发布者</th><td><?php echo $this->sink->user_id ?></td></tr>

            </table>

        </div>


        <div class="panel panel-info ">

            <div class="panel-heading"><font size="5sp"><?php echo $this->sink->name ?></font>&nbsp传感器列表</div>

            <?php
            $sensors = $this->sensors;
            if (count($sensors) == 0) {
                ?>
                <div class="panel-body">
                    <p class="panel-body">此节点下没有传感器</p>
                </div>
            <?php }else{ ?>
            
                <table class="table table-bordered table-hover">
                    <tr>
                        <th width="110">传感器名称</th>
                        <th width="110">传感器类型</th>
                        <th width="50">&nbsp;</th>
                    </tr>
                    <?php foreach ($sensors as $sensor) : ?>
                        <tr>
                            <td><?php echo $sensor->name?></td>
                            <td><?php echo $sensor->type;?></td>
                            <td><a class="btn btn-primary" data-toggle="modal" data-target="#myModal<?php echo $sensor->sensor_id; ?>" >订阅</a>
                            </td>
                        </tr>

                        <?php
                        $form = $this->form;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        ?>
                        <form class="form-inline">
                        <!-- Modal -->
                        <div class="modal fade" id="myModal<?php echo $sensor->sensor_id; ?>" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel" aria-hidden="true" >
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h3 id="myModalLabel" >订阅 </h3><h4 style="color:#48cfad">&nbsp;&nbsp;&nbsp;<?php  echo $sensor->name?><h4>
                                    </div>


                                    <div class="modal-body">
                                        <div class="form-group">

                                            <!-- Single button -->
                                            <!--                 <div class="btn-group"> -->
                                            <!--                     <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> -->
                                            <!--                         推送方式 <span class="caret"></span> -->
                                            <!--                     </button> -->
                                            <!--                     <ul class="dropdown-menu" role="menu" id="send_method" name="send_method"> -->

                                            <!--                     </ul> -->
                                            <!--                 </div> -->

                                            <!--  <label>推送方式</label> <?php echo $this->formSelect($form->get('send_method'));?> -->
                                            <label for="send_method">过滤条件</label>
                                            <div class="btn-group">
                                            <select class="form-control" id="send_method" name="send_method">
                                              <option value="1">电子邮件</option>
                                              <option value="2">手机短信</option>
                                              
                                              
                                            </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="address">邮箱</label>
                                            
                                            <input type="email" class="form-control" id="address" name="address" placeholder="example@example.com">
                                        </div>
                                        <div class="form-group">
                                            <label for="phoneNumber" class="gray">手机号码</label>
                                            
                                            <input type="text" class="form-control" id="phoneNumber" name="phoneNumber" placeholder="暂时不能用" disabled="disabled" >
                                        </div>

                                        <div class="form-group ">
                                            
                                            <!--  <label>过滤条件</label><?php echo $this->formSelect($form->get('filter'));?> -->
                                            <label for="filter">过滤条件</label>
                                            
                                            <select class="form-control" id="filter" name="filter">
                                              <option value="0">无</option>
                                              <option value="1">大于</option>
                                              <option value="2">小于</option>
                                              <option value="3">大于等于</option>
                                              <option value="4">小于等于</option>
                                              <option value="5">等于</option>
                                              <option value="6">不等于</option>
                                              
                                            </select>
                                          
                                        </div>
                                        <div class="form-group">
                                            <label for="threshold_value">条件阈值</label>
                                            
                                            <input type="number"  class="form-control" id="threshold_value" name="threshold_value" placeholder="10">
                                            
                                        </div>

                                        <div class="form-group">
                                           <label for="send_frequency" class="gray">推送频率</label>
                                            <!-- <?php echo $this->formSelect($form->get('send_frequency'));?> -->
 
                                           <!-- <div class="btn-group"> -->
                                            <select class="form-control" id="send_frequency" name="send_frequency">
                                              <option value="5">现在发送</option>
                                              <option value="1">一分钟一次</option>
                                              <option value="2">一小时一次</option>
                                              <option value="3">六小时一次</option>
                                              <option value="4">一天一次</option>
                                              
                                            </select>
                                           
                                        </div>

                                    </div>
                                    <label><?php $sensor_id = $form->get('sensor_id');
                                        $sensor_id->setValue($sensor->id);
                                        
                                        echo $this->formRow($form->get('sensor_id'));?>
                                        
                                        </label>
                                    
                                    <div class="modal-footer">
                                        <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
                                        <?php echo $this->formSubmit($form->get('subscribe'));
                  echo $this->form()->closeTag()?>

                                    </div>

                                </div>
                            </div>
                        </div>
                        </form>
                        <?php
                        echo $this->form()->closeTag()?>
                    <?php
                    endforeach; ?>

                </table>


            
            <?php }?>

        </div>


    </div>


</div>




<div class="clearfix"></div>


</body>
</html>