<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<p>&nbsp;</p>
<p align="center"><strong>订阅首页</strong></p>
<p>&nbsp;</p>

 
<!--引用百度地图API-->
<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.5&ak=EZfQrPMLSMR4YvDnDMwO9r81"></script>

<div style="height:650px;border:#ccc solid 1px;width:100%" id="allmap" ></div>

<script type="text/javascript">
var map = new BMap.Map("allmap");            
var centerPoint = new BMap.Point(110.404, 37.915);
var testPoint = new BMap.Point(116.404,39.915);
map.centerAndZoom(centerPoint,5);                     
map.enableScrollWheelZoom();  

var centerMarker = new BMap.Marker(centerPoint);
var testMarker = new BMap.Marker(testPoint);
map.addOverlay(centerMarker);
map.addOverlay(testMarker);

var tilelayer=new BMap.TileLayer();
tilelayer.getTilesUrl=function(){
 return "layer.gif";
};
map.addTileLayer(tilelayer);

</script>

<?php  $sinks = $this->sinks;
foreach ($sinks as $sink) :?>
<?php
echo "<script> 
var name = \"$sink->name\";
var longitude = \"$sink->longitude\";
var altitude = \"$sink->latitude\";
var point = new BMap.Point(longitude, altitude);
var marker = new BMap.Marker(point); 
marker.addEventListener(\"mouseover\",function(){
		var label = new BMap.Label(\"$sink->name\",{offset:new BMap.Size(20,-10)});
		marker.setLabel(label);
	});
	marker.addEventListener(\"click\",function(e){
		showSinkInfo(\"$sink->id\");
	});
map.addOverlay(marker);
 </script>";
?>
	
<?php endforeach;?>
<script type="text/javascript">
function showSinkInfo(sink_id){
	var url = "/SensorCloud/public/subscriber/sinkinfo/";
	url += sink_id;
	window.location.href=url;
}
</script>
