<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--  
<p>&nbsp;</p>
<p align="center"><strong>订阅首页</strong></p>
<p>&nbsp;</p>
-->
 
<!--引用百度地图API-->

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('home', array(
		                                        'action' => 'index'));?>">首页</a></li>
  <li class="active">服务订阅</li>
</ol>
<div style="height:600px;border:#ccc solid 1px;width:80%;margin-left:auto;margin-right:auto" id="allmap" ></div>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.5&ak=EZfQrPMLSMR4YvDnDMwO9r81"></script>
<script type="text/javascript">
var map = new BMap.Map("allmap");            
var centerPoint = new BMap.Point(110.404, 37.915);
var testPoint = new BMap.Point(116.404,39.915);
map.centerAndZoom(centerPoint,5);                     
map.enableScrollWheelZoom();  

var myIcon = new BMap.Icon("../images/marker.gif",new BMap.Size(100,190),{
	anchor:new BMap.Size(7,25)
});
var centerMarker = new BMap.Marker(centerPoint,{icon:myIcon});
var testMarker = new BMap.Marker(testPoint,{icon:myIcon});
// map.addOverlay(centerMarker);
// map.addOverlay(testMarker);

var tilelayer=new BMap.TileLayer();
tilelayer.getTilesUrl=function(){
 return "layer.gif";
};
map.addTileLayer(tilelayer);

</script>

<?php  $sinks = $this->sinks;
foreach ($sinks as $sink) :?>
<?php
echo "<script> 
var name = \"$sink->name\";
var longitude = \"$sink->longitude\";
var altitude = \"$sink->latitude\";
var point = new BMap.Point(longitude, altitude);
var myIcon = new BMap.Icon('../images/marker.gif',new BMap.Size(14,23),{
	anchor:new BMap.Size(7,25)
});
var marker = new BMap.Marker(point,{icon:myIcon}); 
marker.setTitle(name);
	marker.addEventListener(\"click\",function(e){
		showSinkInfo(\"$sink->id\");
	});
map.addOverlay(marker);
 </script>";
?>
	
<?php endforeach;?>
<script type="text/javascript">
function showSinkInfo(sink_id){
	var url = "/SensorCloud/public/subscriber/sinkinfo/";
	url += sink_id;
	window.location.href=url;
}
</script>
