<script type="text/javascript">
$(function(){
$(".subNav").click(function(){
			$(this).toggleClass("currentDd").siblings(".subNav").removeClass("currentDd")
			$(this).toggleClass("currentDt").siblings(".subNav").removeClass("currentDt")
			
			// 修改数字控制速度， slideUp(500)控制卷起速度
			$(this).next(".navContent").slideToggle(500).siblings(".navContent").slideUp(500);
	})	
})
</script>
<div>
   
    <div class="subNavBox" style=" float:left; width:20%;">
	    <div class="subNav currentDd">用户信息</div>
     	<ul class="navContent " style="display:block">
	        <li><a href="#">用户信息</a></li>
	    	<li><a href="#">修改密码</a></li>
    	</ul>
	    <div class="subNav">发布节点</div>
	    <ul class="navContent">
		    <li><a href="#">我的节点</a></li>
		    <li><a href="../poster/addsink">添加节点</a></li>
    	</ul>
    	<div class="subNav">传感器</div>
    	<ul class="navContent">
			<li><a href="#">我的传感器</a></li>
			<li><a href="#">添加传感器</a></li>
	    </ul>
    </div>
    <div style=" float:left; width:80%;">
           <?php
   $title = '添加发布节点';
   $this->headTitle($title);
   ?>
   <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
       <div>     
           <label><FONT color = "red">请输入节点名称</FONT><?php echo $this->formRow($form->get('name'));?></label>
       </div>
       <div><?php echo $this->formSubmit($form->get('addsink'));
                  echo $this->form()->closeTag()?>
       </div>
   
    </div>
</div>
