<div style="text-align:center;">

   <?php
   $title = '添加发布节点';
   $this->headTitle($title);
   ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
   <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    
    <div>
       <div>     
           <label><font color = "red">&nbsp&nbsp&nbsp请输入用户名</font><?php echo $this->formRow($form->get('user_id'));?></label>
       </div>
       <div>     
           <label><FONT color = "red">请输入节点名称</FONT><?php echo $this->formRow($form->get('name'));?></label>
       </div>
       <div><?php echo $this->formSubmit($form->get('addsink'));
                  echo $this->form()->closeTag()?>
       </div>
    </div>
    
</div>