<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<div style="text-align:center;">

   <?php
   $title = '修改密码';
   $this->headTitle($title);
   ?>
   <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <p>&nbsp;</p>
    <p align="center"><strong>修改密码</strong></p>
    <p>&nbsp;</p>
    <div>
       <div>     
           <label><font color = "red">请输入旧密码</font><?php echo $this->formRow($form->get('oldpassword'));?></label>
       </div>
       <div>     
           <label><FONT color = "red">请输入新密码</FONT><?php echo $this->formRow($form->get('newpassword'));?></label>
       </div>
       <div>     
           <label><FONT color = "red">请确认新密码</FONT><?php echo $this->formRow($form->get('newpassword2'));?></label>
       </div>
       <div><?php echo $this->formSubmit($form->get('changepass'));
                  echo $this->form()->closeTag()?>
       </div>
    </div>
    <p>&nbsp;</p>
</div>