<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<head>
<title>SensorCloud</title>
<link href="/SensorCloud/public/css/bootstrap.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<link href="/SensorCloud/public/css/style.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- webfonts -->
<link href='http://fonts.googleapis.com/css?family=Arimo:400,700'
	rel='stylesheet' type='text/css'>
<!-- webfonts -->
</head>
<div >

   <?php
$title = '修改密码';
$this->headTitle($title);
?>
   <?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
    <div class="page-header" style="margin-top:-30px;">
  <h3>修改密码 </h3>
</div>
	<p>&nbsp;</p>
	<!--  
    <div>
       <div>     
           <label><font color = "red">请输入旧密码</font><?php echo $this->formRow($form->get('oldpassword'));?></label>
       </div>
       <div>     
           <label><FONT color = "red">请输入新密码</FONT><?php echo $this->formRow($form->get('newpassword'));?></label>
       </div>
       <div>     
           <label><FONT color = "red">请确认新密码</FONT><?php echo $this->formRow($form->get('newpassword2'));?></label>
       </div>
       <div><?php
    
echo $this->formSubmit($form->get('changepass'));
    echo $this->form()->closeTag()?>
       </div>
    </div>
    <p>&nbsp;</p>
    -->




</div>

<form class="form-horizontal">
  <div class="form-group" >
    <label for="oldpassword" class="col-sm-2 col-sm-offset-3 control-label">旧密码</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="password" class="form-control" value="" name="oldpassword" onfocus="this.value = '';">
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group" >
    <label for="newpassword" class="col-sm-2 col-sm-offset-3 control-label">新密码</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="password" class="form-control"
						value="" name="newpassword" onfocus="this.value = '';"
						>
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group" >
    <label for="oldpassword" class="col-sm-2 col-sm-offset-3 control-label">请输入邮箱</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="password" class="form-control"
						value="" name="oldpassword2" onfocus="this.value = '';"
						>
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-5 col-sm-7">
    <?php echo $this->formSubmit($form->get('changepass'));
                  echo $this->form()->closeTag()?>
     </div>

 </div>
  <div class="clearfix"></div>
 </form>

<script src="/SensorCloud/public/js/jquery.min.js"></script>
<script src="/SensorCloud/public/js/bootstrap.min.js"></script>