<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

 <div id="myCarousel" class="carousel slide block-center" style="margin:0 40px 0 40px">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item callbacks_container rslides">
        <img class="img-responsive" src="./images/cloud2.jpg" alt="">
					          <div class="slider-caption">
					          	<h1>SCloud<span>+</span></h1>
					         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					         	 <a class="caption-btn" href="#">ReadMore</a>
					          </div>
    </div>
    <div class="item callbacks_container rslides"><img class="img-responsive" src="./images/cloud2.jpg" alt="">
					          <div class="slider-caption">
					          	<h1>SCloud<span>+</span></h1>
					         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					         	 <a class="caption-btn" href="#">ReadMore</a>
					          </div></div>
    <div class="item callbacks_container rslides"><img class="img-responsive" src="./images/cloud2.jpg" alt="">
					          <div class="slider-caption">
					          	<h1>SCloud<span>+</span></h1>
					         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					         	 <a class="caption-btn" href="#">ReadMore</a>
					          </div></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
</div>
</div>

<div class="top-grids text-center">
			<div class="">
		
			
				<div class="col-md-3 col-md-offset-3"  onclick="window.location.href = '<?php
    
echo $this->url('subscriber', array(
        'action' => 'subscriberindex'
    ));
    ?>'">
					<div class="top-grid">
						<img alt="" src="images/upload.png"> 
						<h3><?php echo $this->translate('服务订阅') ?></h3>
						 <p></p>
					</div>
				</div>
				<div class="col-md-3" onclick="window.location.href = '<?php
    
echo $this->url('poster', array(
        'action' => 'posterindex'
    ));
    ?>'">
					<div class="top-grid">
						<img alt="" src="images/download.png">
						<h3><?php echo $this->translate('服务发布') ?></h3>
						 <p></p>
					</div>
				</div>
				
				<div class="col-md-3"></div>
				
				<div class="clearfix"></div>
			</div>
			
</div>
		
<!-- </div> -->
		


