<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

   
<div class="benner">
				<!-- slider -->
				<!--- img-slider --->
				<div class="img-slider">
						<!----start-slider-script---->
					<script src="./js/responsiveslides.min.js"></script>
					 <script>
					    // You can also use "$(window).load(function() {"
					    $(function () {
					      // Slideshow 4
					      $("#slider4").responsiveSlides({
					        auto: true,
					        pager: true,
					        nav: true,
					        speed: 500,
					        namespace: "callbacks",
					        before: function () {
					          $('.events').append("<li>before event fired.</li>");
					        },
					        after: function () {
					          $('.events').append("<li>after event fired.</li>");
					        }
					      });
					
					    });
					  </script>
					<!----//End-slider-script---->
					<!-- Slideshow 4 -->
					    <div  id="top" class="callbacks_container">
					      <ul class="rslides" id="slider4">
					        <li>
					          <img class="img-responsive" src="./images/cloud2.jpg" alt="">
					          <div class="slider-caption">
					          	<h1>SCloud<span>+</span></h1>
					         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					         	 <a class="caption-btn" href="#">ReadMore</a>
					          </div>
					        </li>
					        <li>
					          <img src="./images/cloud2.jpg" alt="">
					           <div class="slider-caption">
					          	<h1>medical<span>+</span></h1>
					          	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					            <a class="caption-btn" href="#">ReadMore</a>
					          </div>
					        </li>
					        <li>
					          <img src="./images/cloud2.jpg" alt="">
					           <div class="slider-caption">
					           	<h1>medical<span>+</span></h1>
					           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
					           <a class="caption-btn" href="#">ReadMore</a>
					          </div>
					        </li>
					      </ul>
					    </div>
					    <div class="clearfix"> </div>
					</div>
						<!-- slider -->
</div>
<!-- /banner -->
    
<div class="top-grids text-center">
			<div class="">
		
			
				<div class="col-md-3 col-md-offset-3"  onclick="window.location.href = '<?php
    
echo $this->url('subscriber', array(
        'action' => 'subscriberindex'
    ));
    ?>'">
					<div class="top-grid">
						<img alt="" src="images/upload.png"> 
						<h3><?php echo $this->translate('服务订阅') ?></h3>
						 <p></p>
					</div>
				</div>
				<div class="col-md-3" onclick="window.location.href = '<?php
    
echo $this->url('poster', array(
        'action' => 'posterindex'
    ));
    ?>'">
					<div class="top-grid">
						<img alt="" src="images/download.png">
						<h3><?php echo $this->translate('服务发布') ?></h3>
						 <p></p>
					</div>
				</div>
				
				<div class="col-md-3"></div>
				
				<div class="clearfix"></div>
			</div>
			
</div>
		
<!-- </div> -->
		


