<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<div style="text-align:center;">

   <?php
   $title = '用户登录';
   $this->headTitle($title);
   ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
   <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    
    
<form class="form-horizontal">
  <div class="form-group" >
    <label for="username" class="col-sm-2 col-sm-offset-3 control-label">用戶名</label>
    <div class="col-sm-4" style="margin-bottom: 10px">
      <input type="text" class="form-control" id="username" placeholder="Username" name="username">
    </div>
    <div class="col-sm-3"></div>
  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 col-sm-offset-3 control-label">密码</label>
    <div class="col-sm-4" >
      <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset--1 col-sm-11">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset--1 col-sm-11">
     
      <button type="submit" class="btn btn-default" name="login">登录</button>
      <?php 
                  echo $this->form()->closeTag()?>
                  
              

    </div>
  </div>
  <div class="clearfix"></div>
</form>
    
</div>