<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>用户中心</title>
<?php $session = new \Zend\Session\Container('user');?>
</head>

<body>
<p>&nbsp;</p>
<p align="center"><strong>用户中心</strong></p>
<p>&nbsp;</p>
<p><strong>个人信息</strong></p>
<div align="center">用户名： <?php echo $this->name?></div>
<p>&nbsp;</p>
<p><strong>订阅中心</strong></p>
<div align="center">订阅服务个数： <?php echo $this->sub_num?></div>
<p>&nbsp;</p>
<p><strong>服务发布</strong></p>
<div align="center">发布结点个数： <?php echo $this->sink_num?></div>
<div align="center">注册服务个数： <?php echo $this->sensor_num?></div>
<div align="center">发布服务个数： <?php echo $this->post_num?></div>
<p>&nbsp;</p>
</body>
</html>