<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<div style="text-align:center;">

   <?php
   $title = '新用户注册';
   $this->headTitle($title);
   ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
   <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    
   
    
<form class="form-horizontal">
  <div class="form-group" >
    <label for="email" class="col-sm-2 col-sm-offset-3 control-label">请输入邮箱</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group">
    <label for="username"  class="col-sm-2 col-sm-offset-3 control-label">设置用户名</label>
    <div class="col-sm-4 " style="margin-bottom: 10px">
    <input type="text" class="form-control" id="username" placeholder="Jane Doe" name="username">
    </div>
  </div>
  
  <div class="form-group">
    <label for="password" class="col-sm-2 col-sm-offset-3 control-label">请输入密码</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group">
    <label for="password2" class="col-sm-2 col-sm-offset-3 control-label">请输入密码</label>
    <div class="col-sm-4 " style="margin-bottom: 10px" >
      <input type="password" class="form-control" id="password2" placeholder="Password" name="password2">
    </div>
    <div class="col-sm-3"></div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset--1 col-sm-11">
    <label>  是否为发布方？  <?php echo $this->formradio($form->get('poster'),\Zend\form\view\helper\FormRadio::LABEL_PREPEND);?></label>

<!--     <label>  是否为发布方？<input type="checkbox" name="poster"> -->
<!--         </label> -->
    </div>
    

    <div class="col-sm-4" >
<!--         <label class="radio-inline"> -->
<!--           <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> 1 -->
<!--         </label> -->
<!--         <label class="radio-inline"> -->
<!--          <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> 2 -->
<!--         </label> -->
    
   </div>
  <div class="col-sm-3"></div>
 </div>
  
 <div class="form-group">
    <div class="col-sm-offset--1 col-sm-11">
    <?php echo $this->formSubmit($form->get('submit'));
                  echo $this->form()->closeTag()?>
     </div>

 </div>
 <div class="clearfix"></div>
</form>