<div style="text-align:center;">

   <?php
   $title = '新用户注册';
   $this->headTitle($title);
   ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
   <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('application', array('action' => 'register')));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    
    <div>
       <div>     
           <label><font color = "red">请输入邮件</font><?php echo $this->formRow($form->get('email'));?></label>
       </div>
       <div>     
           <label>昵称为选填<?php echo $this->formRow($form->get('uname'));?></label>
       </div>
       <div>     
           <label><font color = "red">请输入密码</font><?php echo $this->formRow($form->get('password'));?></label>
       </div>
       <div>     
           <label><font color = "red">请确认密码</font><?php echo $this->formRow($form->get('password2'));?></label>
       </div>
       <div>     
           <label><font color = "red">是否发布方？</font><?php echo $this->formradio($form->get('poster'),\Zend\form\view\helper\FormRadio::LABEL_PREPEND);?></label>
       </div>
       <div><?php echo $this->formSubmit($form->get('submit'));
                  echo $this->form()->closeTag()?>
       </div>
    </div>
    
</div>