<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>userframe</title>

</head>
<frameset cols="10%,20%,60%,10%" >
    <frame frameborder="0">
    <frame src="../application/userguide" frameborder = "0"/>
    <frame src="../application/mycenter" frameborder = "0" name = "show"/>
    <frame frameborder="0">
    <noframes>
    <body>
    <p>This page uses frames. The current browser you are using does not support frames.</p>
    </body>
    </noframes>
</frameset>
</html>