<div class="hero-unit">
    <h1><center><?php echo sprintf($this->translate('Welcome to %sSensorCloud%s'), '<span class="zf-green">', '</span>') ?></center></h1>
    
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('订阅信息') ?></h2>
        <p><?php echo sprintf($this->translate('您可以选择某一传感器，以获得其最新数据')) ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('详细') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('发布信息') ?></h2>
        <p><?php echo sprintf($this->translate('您可以添加传感器，上传其数据')) ?></p>
        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('详细') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('联系我们') ?></h2>
       <p><?php echo sprintf($this->translate('想要了解更多信息，请联系我们')) ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('详细') ?> &raquo;</a></p>
   </div>
</div>
