<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
    <link href="/SensorCloud/public/css/bootstrap.css" rel='stylesheet'
          type='text/css' />
    <!-- Custom Theme files -->
    <link href="/SensorCloud/public/css/style.css" rel='stylesheet'
          type='text/css' />
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Arimo:400,700'
          rel='stylesheet' type='text/css'>
    <!-- webfonts -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<?php
$title = '我的传感云服务';
$this->headTitle($title);
?>
<div class="page-header" style="margin-top:-30px;">
    <h3>传感云服务列表 </h3>
</div>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('poster',
            array('action'=>'mysink'));?>">节点列表</a></li>
    <li class="active"><?php echo $this->sink_name?></li>
</ol>
<?php $sensors = $this->sensors;
if(count($sensors)==0){?>
    <p align="center">此节点下没有传感云服务</p>
<?php }else{ ?>
    <table  class="table table-bordered table-hover"  align="center" bgcolor = "#99CCFF" >
        <tr>
            <th width="110">传感云服务名称</th>
            <th width="110">传感云服务类型</th>
            <th width="110">是否已发布？</th>
            <th width="70">&nbsp;</th>
            <th width="70">&nbsp;</th>
        </tr>
        <?php foreach ($sensors as $sensor) : ?>
            <tr>
                <td><?php echo $sensor->name;?></td>
                <td><?php echo $sensor->type;?></td>
                <td><?php if($sensor->post == 1) echo "是";
                    else echo "否" ?></td>
                <td><?php if($sensor->post == 0) {?>
                        <script language="javascript">
                            function postcfm() {
                                if (!confirm("确认发布该服务？")) {
                                    window.event.returnValue = false;
                                }
                                else{
                                    postsuc();
                                }
                            }
                            function postsuc(){
                                if(confirm("发布成功！")){
                                    window.href="<?php echo $this->url('poster',
                     array('action'=>'mysensor','sink_id' => $sensor->sink_id));?>"
                                }
                            }
                        </script>
                        <a href="<?php echo $this->url('poster',
                            array('action'=>'postsensor','sink_id' => $sensor->sink_id,'sensor_id' => $sensor->id));?>" onClick="postcfm()">发布</a>
                    <?php }else{?>
                        <script language="javascript">
                            function canpostcfm() {
                                if (!confirm("确认取消发布该服务？")) {
                                    window.event.returnValue = false;
                                }
                            }
                        </script>
                        <a href="<?php echo $this->url('poster',array('action'=>'canclepostsensor','sink_id' => $sensor->sink_id,'sensor_id' => $sensor->id));?>" onClick="canpostcfm()">取消发布</a>
                    <?php }?>
                </td>
                <td>
                    <script language="javascript">
                        function delcfm() {
                            if (!confirm("确认删除该传感云服务？")) {
                                window.event.returnValue = false;
                            }
                        }
                    </script>
                    <a href="<?php echo $this->url('poster',
                        array('action'=>'deletesensor','sink_id' => $sensor->sink_id,'sensor_id' => $sensor->id));?>" onClick="delcfm()">删除</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php }?>
<div align="center" style="margin-top:15px; ">
    <button type="button" onclick="window.location.href = '<?php echo $this->url('poster',
        array('action'=>'addsensor','sink_id' => $this->sink_id));?>'"><?php echo $this->translate('添加一个传感云服务') ?></button>
</div>

<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
<script src="/SensorCloud/public/js/bootstrap.min.js"></script>