<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php
$title = '我的发布节点';
$this->headTitle($title);
?>
<p>&nbsp;</p>
<p align="center"><strong>我的发布节点</strong></p>
<p>&nbsp;</p>

<?php $sinks = $this->sinks;
      if(count($sinks)==0){?>
<p align="center">当前没有发布节点</p>
<?php }else{ ?>
<table border="1" align="center" bgcolor = "#99CCFF" >
<tr>
    <th width="110">节点名称</th>
    <th width="110">节点ID</th>
    <th width="117">节点位置</th>
    <th width="100">&nbsp;</th>
</tr>
<?php foreach ($sinks as $sink) : ?>
<tr>
    <td><?php echo $sink->name;?></td>
    <td><?php echo $sink->id;?></td>
    <td>(<?php echo $sink->longitude;?>,<?php echo $sink->latitude;?>)</td>
    <td>
    <a href="<?php echo $this->url('poster',
            array('action'=>'mysensor','sink_id' => $sink->id));?>">查看</a>
        <script language="javascript">
         function delcfm() {
            if (!confirm("确认删除该节点？")) {
                 window.event.returnValue = false;
             }
         }
        </script>
        <a href="<?php echo $this->url('poster',
            array('action'=>'deletesink','sink_id' => $sink->id));?>" onClick="delcfm()">删除</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php }?>
<div align="center" style="margin-top:15px; ">
     <button type="button" onclick="parent.parent.location.href = '<?php echo $this->url('poster',
                array('action'=>'posterindex'));?>'"><?php echo $this->translate('添加一个节点') ?></button>
</div>