<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<link href="/SensorCloud/public/css/bootstrap.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<link href="/SensorCloud/public/css/style.css" rel='stylesheet'
	type='text/css' />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- webfonts -->
<link href='http://fonts.googleapis.com/css?family=Arimo:400,700'
	rel='stylesheet' type='text/css'>
<!-- webfonts -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<?php
$title = '我的发布节点';
$this->headTitle($title);
?>

<div class="page-header" style="margin-top:-30px;">
  <h3>我的发布节点 </h3>
</div>


<?php $sinks = $this->sinks;
      if(count($sinks)==0){?>
<p align="center">当前没有发布节点</p>
<?php }else{ ?>
<table  class="table table-bordered table-hover"  align="center" bgcolor = "#99CCFF" >
<tr>
    <th >节点名称</th>
    <th>节点授权号</th>
    <th >节点位置</th>
    <th >&nbsp;</th>
</tr>
<?php foreach ($sinks as $sink) : ?>
<tr>
    <td><?php echo $sink->name;?></td>
    <td><?php echo $sink->id;?></td>
    <td>(<?php echo $sink->longitude;?>,<?php echo $sink->latitude;?>)</td>
    <td>
    <a href="<?php echo $this->url('poster',
            array('action'=>'mysensor','sink_id' => $sink->id));?>">查看</a>
        <script language="javascript">
         function delcfm() {
            if (!confirm("确认删除该节点？")) {
                 window.event.returnValue = false;
             }
         }
        </script>
        <a href="<?php echo $this->url('poster',
            array('action'=>'deletesink','sink_id' => $sink->id));?>" onClick="delcfm()">删除</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php }?>
<div align="center" style="margin-top:15px; ">
     <button type="button" onclick="parent.parent.location.href = '<?php echo $this->url('poster',
                array('action'=>'posterindex'));?>'"><?php echo $this->translate('添加一个节点') ?></button>
</div>
<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
<script src="/SensorCloud/public/js/bootstrap.min.js"></script>